"""Build script: embeds public/index.html into api/frontend.py"""
import base64
from pathlib import Path

ROOT = Path(__file__).parent

# Read HTML
html = (ROOT / "public" / "index.html").read_text(encoding="utf-8")

# Read image as base64
img_path = ROOT / "public" / "image.png"
if img_path.exists():
    img_b64 = base64.b64encode(img_path.read_bytes()).decode()
    data_uri = f"data:image/png;base64,{img_b64}"
    # Replace src="image.png" with data URI so image works without file access
    html = html.replace('src="image.png"', f'src="{data_uri}"')
    html = html.replace("src='image.png'", f"src='{data_uri}'")

# Write to api/frontend.py
out = ROOT / "api" / "frontend.py"
escaped = html.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
out.write_text(
    '# Auto-generated by embed_frontend.py — DO NOT EDIT\n'
    '# Frontend HTML with MongoDB logo embedded as base64\n\n'
    'INDEX_HTML = """\n' + escaped + '\n"""\n',
    encoding="utf-8"
)
print(f"Written {out} ({len(html)} bytes HTML, image embedded: {img_path.exists()})")
