"""Build script: embeds public/index.html, style.css, and app.js into api/frontend.py"""
import base64
from pathlib import Path

ROOT = Path(__file__).parent

# Read HTML
html = (ROOT / "public" / "index.html").read_text(encoding="utf-8")

# Read and inline style.css
css_path = ROOT / "public" / "style.css"
if css_path.exists():
    css_content = css_path.read_text(encoding="utf-8")
    html = html.replace('<link rel="stylesheet" href="style.css"/>', f'<style>\n{css_content}\n</style>')

# Read and inline local JS scripts dynamically
import re
def inline_script(match):
    src = match.group(1)
    if src.startswith("http") or src.startswith("//") or src.startswith("https"):
        return match.group(0)
    js_path = ROOT / "public" / src
    if js_path.exists():
        js_content = js_path.read_text(encoding="utf-8")
        return f'<script>\n{js_content}\n</script>'
    return match.group(0)

html = re.sub(r'<script src="([^"]+)"></script>', inline_script, html)

# Read image as base64
img_path = ROOT / "public" / "image.png"
if img_path.exists():
    img_b64 = base64.b64encode(img_path.read_bytes()).decode()
    data_uri = f"data:image/png;base64,{img_b64}"
    # Replace src="image.png" with data URI so image works without file access
    html = html.replace('src="image.png"', f'src="{data_uri}"')
    html = html.replace("src='image.png'", f"src='{data_uri}'")

# Write to api/frontend.py
out = ROOT / "api" / "frontend.py"
escaped = html.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
out.write_text(
    '# Auto-generated by embed_frontend.py — DO NOT EDIT\n'
    '# Frontend HTML with MongoDB logo, CSS, and JS embedded\n\n'
    'INDEX_HTML = """\n' + escaped + '\n"""\n',
    encoding="utf-8"
)
print(f"Written {out} ({len(html)} bytes compiled single-page HTML, image embedded: {img_path.exists()})")
